rootProject.name = "flowminer"
include("analysis:jira-importer")
include("analysis:jira-cli")
include("analysis:git-importer")
include("analysis:github-importer")
include("analysis:gitcli")
include("analysis:github-cli")
include("analysis:fmsh")
include("analysis:model")
include("shared")
include("analysis:architecture-tests")
include("analysis:gitlab-importer")
include("analysis:gitlab-cli")